services:
  # Pybricks Code
  pybrickscode:
    container_name: ${PYBRICKSCODE_CONTAINER_NAME:-PybricksCode}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_TAG: ${NODE_TAG:-14.18.2}
        PYBRICKSCODE_TAG: ${PYBRICKSCODE_TAG:-v1.2.0-beta.1}
    restart: ${RESTART:-unless-stopped}
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - ${PYBRICKSCODE_PORT:-80}:80
